export const MOCK_KPI_PAYLOAD = {
  items: [
    {
      id: "STR-REAL",
      ts: "2024-10-01T08:00:00Z",
      regime: "normal",
      risk_band: "medium",
      dp_excess_mbar: 410,
      prob_breach7d: 0.52,
      prob_breach7d_raw: 0.5,
      threshold_eff: 0.48,
    },
    {
      id: "STR-REAL",
      ts: "2024-10-02T08:00:00Z",
      regime: "normal",
      risk_band: "medium",
      dp_excess_mbar: 420,
      prob_breach7d: 0.55,
      prob_breach7d_raw: 0.52,
      threshold_eff: 0.48,
    },
    {
      id: "STR-REAL",
      ts: "2024-10-03T08:00:00Z",
      regime: "post_startup",
      risk_band: "medium",
      dp_excess_mbar: 435,
      prob_breach7d: 0.58,
      prob_breach7d_raw: 0.55,
      threshold_eff: 0.47,
    },
    {
      id: "STR-REAL",
      ts: "2024-10-04T08:00:00Z",
      regime: "post_startup",
      risk_band: "high",
      dp_excess_mbar: 455,
      prob_breach7d: 0.61,
      prob_breach7d_raw: 0.6,
      threshold_eff: 0.46,
    },
    {
      id: "STR-REAL",
      ts: "2024-10-05T08:00:00Z",
      regime: "post_startup",
      risk_band: "high",
      dp_excess_mbar: 470,
      prob_breach7d: 0.64,
      prob_breach7d_raw: 0.63,
      threshold_eff: 0.45,
    },
    {
      id: "STR-REAL",
      ts: "2024-10-06T08:00:00Z",
      regime: "post_startup",
      risk_band: "high",
      dp_excess_mbar: 485,
      prob_breach7d: 0.66,
      prob_breach7d_raw: 0.65,
      threshold_eff: 0.45,
    },
  ],
  explanation: {
    summary: "Differential pressure is trending upward and approaching the engineered threshold.",
    reasons: [
      "DP trend has risen 18% over the last 7 days.",
      "Probability of breach exceeds the tuned threshold for the current regime.",
      "Recent backwash interval extended beyond recommended schedule.",
    ],
    actions: [
      "Inspect upstream separation train for fouling and drain blockages.",
      "Plan a strainer cleaning during the next 48-hour maintenance window.",
      "Verify DP transmitters calibration before next product changeover.",
    ],
  },
  meta: {
    alerts_fired: 3,
    last_clean_date: "2024-09-22",
    points: 72,
    risk_band_counts: { high: 5, medium: 9, low: 6 },
  },
};
